### ISSUE TITLE
Hello world programs

### ISSUE THREAD

**Issue by amirouche** [scheme-live/live#13]
Make the test called `live/check-0000-hello-schemer` and `live/check-0001-hello-schemer-star` pass green on those implementations:

- [x] #24
- [x] #18
- [ ] #26
- [x] #21
- [x] #32
- [x] #19
- [x] #20
- [x] #28
- [x] #27
- [x] #22
- [x] #30
- [x] #23
- [ ] #25
- [ ] #29
- [ ] #31
- [ ] #33
- [ ] Your fantastic Scheme implementation...

**Comment by lassik** [comment]
Bones is an experimental compiler from one of the Chicken hackers.

Is Racket feasible to support?

The others are definitely imporant.

More:

* Kawa
* Gauche
* Chibi

**Comment by lassik** [comment]
Sagittarius is actively developed and its maintainer is very helpful.

STklos likewise, and it's just getting `define-library` support.

**Comment by lassik** [comment]
MIT Scheme's define-library support is also brand new, but it should mostly work.

Bigloo doesn't have define-library, so we probably can't support Bigloo until it adds that.

**Comment by amirouche** [comment]
Re bigloo, maybe it support filename extensions such as `.bigloo.scm` ? We can then special case it.

NB: `define-library` is not a strong requirement, as long as it is possible to override default import machinery with e.g. extensions.

**Comment by amirouche** [comment]
Re gerbil

- `schemers/gerbil` image is too old, see https://github.com/scheme-containers/gerbil/issues/1
- `gerbil/scheme` image use ubuntu 18.04, where `env` does not support `--split-strings="foo bar"`, see https://github.com/vyzo/gerbil/issues/642

**Comment by amirouche** [comment]
Re Guile:
- `schemers/guile` is buggy https://github.com/scheme-containers/guile/issues/1

**Comment by amirouche** [comment]
Re MIT:
- I can't figure how to make it eval / run some code

**Comment by amirouche** [comment]
Re chicken:
- csi is buggy, csc does not work, neither csm

**Comment by amirouche** [comment]
Re stklos:
- `stklos/stklos` official image is buggy;
- `schemers/stklos` can't run `local/bin/hello` missing `scheme` module.

**Comment by lassik** [comment]
> Re bigloo, maybe it support filename extensions such as `.bigloo.scm` ? We can then special case it.

It doesn't support RnRS libraries at all; it has its own module system.

> NB: `define-library` is not a strong requirement, as long as it is possible to override default import machinery with e.g. extensions.

That sounds a bit magical for something that's just a library collection. Yuni does that; maybe Live can run on top of Yuni?

**Comment by amirouche** [comment]
See the branch https://github.com/scheme-live/live/tree/hello-schemer it can't be merged in master at this time, and there is single commit at this time https://github.com/scheme-live/live/commit/af0c67f62bbfc1580ff0b0540fb8a9f8176a5f81.

I will work on #15, and include benchmarks #12 in branch forked from the `hello-schemer` branch.

**Comment by lassik** [comment]
Looks good!

Please add your nickname at the start of the branch names so we know who owns what branch. (No need to rename the current branches, but in the future.)

**Comment by amirouche** [comment]
Closing this in favor of [Scheme specific issues](https://github.com/scheme-live/live/issues?q=is%3Aissue+is%3Aopen+label%3Ascheme).
