### ISSUE TITLE
Copy ruse-json and make it work with all schemes

### ISSUE THREAD

**Issue by amirouche** [scheme-live/live#15]

**Comment by lassik** [comment]
This is #1 priority on my personal wishlist :p

**Comment by amirouche** [comment]
https://github.com/scheme-live/live/pull/39

**Comment by amirouche** [comment]
Need to update gauche, blocked by https://github.com/shirok/Gauche/issues/785

**Comment by amirouche** [comment]
There is blocking issues with mit, cyclone and chicken.

**Comment by amirouche** [comment]
It works, the test suite would love some more care. I will move onto something else, until someone notice.
