### ISSUE TITLE
setup forge.scheme.org

### ISSUE THREAD

**Issue by amirouche** [scheme-live/live#3]
Deploy forge.scheme.org on my dedicated machine, setup git, hub, build, and list.

**Comment by lassik** [comment]
What software/services should forge.scheme.org contain?

**Comment by amirouche** [comment]
It seems to me starting with services I mentioned are the essential ones:

- git: for git repositories
- hub: aka. project page
- build: for ci
- list: for mailing lists
- todo: for issues (that I forgot in the above list)

There is also:

- dispatch: to ping external service or something
- paste: for pasting snippets!

I might as well deploy everything, since dispatch and paste are easy. The
most difficult might be in order list, build and git.

**Comment by lassik** [comment]
Wow, quite a big undertaking! For transparency, we should discuss on the schemeorg mailing list before adding significant new subdomains so everyone who follows the domain will notive; can you copy your message there?

**Comment by amirouche** [comment]
re undertaking: yeah, but it is packaged in debian, and many have tried,
and succeed before me.

I just posted the issue so that I have a reminder. I will first experiment
locally, then run it a few weeks for myself, and then request
forge.scheme.org.

I am wary to announce a project, for which I have nothing even remotely
started. Let's reconsider asking scheme.org when I have a local setup?

**Comment by lassik** [comment]
Sure, sounds good!

Where does the name "forge" come from, like SourceForge?

Would this be for the entire Scheme community (those who want to use it) or just for the common library collection?

**Comment by amirouche** [comment]
I lost interest at this time.

**Comment by lassik** [comment]
Sure. Setting up a server is a big effort. I may try setting up Gitea or GitLab if I get the energy.
